### ISSUE TITLE
Please Bump Version

### ISSUE THREAD

**Issue by moredhel** [kilianc/shared-git-hooks#13]
Hi, 
I'm using a project which depends on this repo, and am having issues with your package.
I looked through your master code, and you have indeed fixed the problem (see last commit regarding _hook.sh.tpl_.
Thanks for merging that change, could you also bump the version (1.2.2?) and push the new package to npm as the change hasn't propogated out.

Thanks for the project!

**Comment by Minoru** [comment]
Bump. (Sorry for not using Reactions, but it's been three months since the issue has been opened, and no response.)
