### ISSUE TITLE
error on line 6, command not found

### ISSUE THREAD

**Issue by joh-klein** [kilianc/shared-git-hooks#2]
This happens whenever I do anything which could invoke a git hook under windows

```
.git/hooks/post-checkout: line 6: C:Program: command not found
.git/hooks/post-checkout: line 6: C:Windowssystem32: command not found
```

The fix is to wrap PATH in parentheses. 

https://github.com/kilianc/shared-git-hooks/blob/develop/index.js#L26

I'll try to get you a PR

**Comment by joh-klein** [comment]
Quick question: why do you have the PATH variable at all?
https://github.com/kilianc/shared-git-hooks/blob/develop/hook.sh.tpl#L6

**Comment by kilianc** [comment]
@joh-klein take a look at https://github.com/kilianc/shared-git-hooks#assumption I beasically freeze your path so that programs using a different shell can still access custom paths.

**Comment by joh-klein** [comment]
Is it really necessary to freeze the path when you install your module? In Windows I just ran into the problem, that the path is different from when npm installs the module and git runs it. 

``` bash
echo $PATH
echo ""
node -e "console.log(process.env.PATH);"
```

results in

```
/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Users/IEUser/AppData/Roaming/nvm:/c/Program Files/nodejs:/c/Program Files/nodejs:/cmd:/mingw32/bin:/usr/bin:/c/Users/IEUser/AppData/Roaming/npm

C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\IEUser\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw32\bin;C:\Program Files\Git\usr\bin;C:\Users\IEUser\AppData\Roaming\npm
```

In other words: the newly opened shell is completely different to the first one. Nothing works, basically.

**Comment by kilianc** [comment]
@joh-klein I am sorry you are experiencing this, the `PATH` freezing is really important on *nix systems to allow git GUIs to use your custom binaries like `nvm` etc.

Again this module has not been written and or tested for windows users. I am happy to do that but I am not a Windows user myself and I have no way or knowledge to maintain that part.

**Comment by joh-klein** [comment]
I am not using windows by choice … :)
I think I found a solution. PR incoming.

**Comment by joh-klein** [comment]
`sh -c 'echo ${PATH}'` forces Windows to use bash for the PATH discovery. There were no differences on linux.

**Comment by joh-klein** [comment]
@kilianc Is there anything else I can do, to get this merged and closed?

**Comment by kilianc** [comment]
@joh-klein I really appreciate you contribution I really do but work is getting in the way of my open source projects. I'll try to work on this this week

**Comment by joh-klein** [comment]
No sweat. Just wanted to make sure, that the travis errors are not the ones stopping this from getting merged.
